spec:
  template:
    spec:
      containers:
        - name: iris-api
          image: us-central1-docker.pkg.dev/second-capsule-472911-g7/iris-repo/iris-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
