name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Install dependencies
        run: pip install pytest dvc-gs
    
      - name: Authenticate GCP
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set project YOUR_PROJECT_ID

    
      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Pull data & model
        run: dvc pull -r mygcs

      - name: Run tests
        run: pytest -v -s tests/test_pipeline.py > report.txt

      - name: Post CML comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### ✅ Pytest Report" > report.md
          cat report.txt >> report.md
          cml comment create report.md
