name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install "dvc[gs]==2.22.1" "pytest==8.4.2" "cml==0.11.7" "joblib==1.3.2" "pandas==2.1.1" "scikit-learn==1.3.2"

      - name: Pull data & model
        run: dvc pull -r mygcs

      - name: Run tests
        run: pytest -v -s tests/test_pipeline.py > report.txt

      - name: Post CML comment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "### ✅ Pytest Report" > report.md
          cat report.txt >> report.md
          cml comment create report.md
